### ISSUE TITLE
Cannot enable 2factor auth for backend user

### ISSUE THREAD

**Issue by kvonspiczak** [codeFareith/cf_google_authenticator#39]
# Bug report

## Prerequisites
- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

## Description:
I'm getting a bunch of deprecation notices whenever I try to add/edit a be_user and I can't enable the checkbox provided by this extension.
	
TYPO3 Deprecation Notice
Core: Error handler (BE): TYPO3 Deprecation Notice: CodeFareith\CfGoogleAuthenticator\Traits\GeneralUtilityObjectManager will be removed in v1.2.0. in /var/www/html/web/typo3conf/ext/cf_google_authenticator/Classes/Traits/GeneralUtilityObjectManager.php line 39

Also after checking the 2fauth checkbox and saving, TYPO3 backend reloads and the checkbox is unchecked again. I can't properly enable it. Tried including your typoscript template, DB compare but no success.
## Steps to reproduce:
1. Go to 'backend users'
2. Click on 'add or edit'
3. Go to the authenticator checkbox and try enabling & saving the user
4. See unchecked checkbox & deprecation notices

## Expected results:
A checked checkbox that stays checked and activates the 2f auth behavior for the given user.
## Actual results:
Unchecked checkbox after checking and saving.

## Environment
TYPO3 v8.27

## Screenshot(s)
![image](https://user-images.githubusercontent.com/2630690/61043305-317b3e00-a3d6-11e9-9698-416149e777f7.png)

**Comment by xperseguers** [comment]
Confirming this problem. Following hooks are impacted:

* `FeLogin`
* `TCEMain`
* `UserSettings`

as they import the traits which has triggers the deprecation notice.

Solution: either remove the call to `trigger_error()` in `\CodeFareith\CfGoogleAuthenticator\Traits\GeneralUtilityObjectManager::objectManager` or get rid of the trait in your own extension.

**Comment by xperseguers** [comment]
BTW, in production context this may show the flash message but in development context, the backend is just not usable anymore:

![crash](https://user-images.githubusercontent.com/646805/63001893-eb057d00-be74-11e9-994b-8840c5bbe5a2.png)

**Comment by xperseguers** [comment]
After fixing the notice/crash, I cannot reproduce the other documented problem where the checkbox is not ticked upon saving.

What I did:

* Open my user settings from toolbar which had 2FA enabled
* Uncheck 2FA
* Save
* Check 2FA
* Scan barcode
* Enter security code
* Save
* Checkbox is still ticked

**Comment by kvonspiczak** [comment]
@xperseguers thanks for checking out this issue! I can confirm that the checkbox stays checked after removing the `trigger_error()` call.

**Comment by xperseguers** [comment]
Great news @kvonspiczak, now waiting for @codeFareith to press the magic merge button then :)

**Comment by codeFareith** [comment]
I just merged your pull request.
Thank you for your commitment, @xperseguers.

Notice: Currently the fix is only available via GitHub; not via the TER.

FYI @kvonspiczak

**Comment by sascha-schieferdecker** [comment]
I think this bug is not solved. I installed the dev-master by 

`composer require codefareith/cf-google-authenticator:dev-master` 

on TYPO3 9.5.9 and verified that I am using the latest commit. There are no deprecation notices in the logs. But on saving the user no values are persisted to the database.

Any idea what might trigger this behaviour?
